### ISSUE TITLE
按教程部署后报错

### ISSUE THREAD

**Issue by qiuyeshengsheng** [TwooSix/Alist-MikananiRss#36]
按教程部署后运行python3 -m alist_mikananirss --config /usr/python/lib/python3.11/site-packages/alist_mikananirss/config.yaml提示错误
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/python/lib/python3.11/site-packages/alist_mikananirss/__main__.py", line 5, in <module>
    sys.exit(alist_mikananirss.main())
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/python/lib/python3.11/site-packages/alist_mikananirss/__init__.py", line 33, in main
    asyncio.run(run())
  File "/usr/python/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/python/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/python/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/python/lib/python3.11/site-packages/alist_mikananirss/__init__.py", line 22, in run
    initializer.init_extrator() 
  File "/usr/python/lib/python3.11/site-packages/alist_mikananirss/common/initializer.py", line 67, in init_extrator
    raise ValueError("Invalid rename config, extractor is required")
ValueError: Invalid rename config, extractor is required
系统环境 centos7.9,python3.11.0 pip22.3

**Comment by TwooSix** [comment]
cfg格式错了，报错提示你使用了rename项但没有填extractor

**Comment by TwooSix** [comment]
抱歉...我发现我的主分支的readme的cfg示例是错的，后面改改，你如果不用重命名功能的话整块删掉即可，如果要用的话，可以参考完整配置示例填上gpt的token，因为新版本我把正则重命名给删了，只能用gpt了。

**Comment by qiuyeshengsheng** [comment]
好的，感谢回复，我去试试

**Comment by TwooSix** [comment]
fixed in 495b3cc
